myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

import student

urlpatterns = [
    path('', include('myapp.urls')),
    path('clg', include('student.urls')),
    path('admin/', admin.site.urls),
]

student/urls.py
from django.urls import path

from . import views

app_name = 'student'
urlpatterns = [
    path('', views.homeview, name='homeview'),
    path('students/', views.studentlistView, name='studentlistView'),
    path('lecturers/', views.lecturerslistView, name='lecturerslistView'),
    path('courses/', views.courselistView, name='courselistView'),
    path('subjects/', views.subjectslistView, name='subjectslistView'),
    path('courseDetails/<int:record_id>/', views.coursedetailView, name='coursedetailView'),
    path('subject-lectures/<int:record_id>/', views.subjectlecturerView, name="subjectlecturerView"),
    ]

myapp/models.py
import datetime

from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

student/models.py
from django.core.validators import MaxValueValidator
from django.db import models


# Create your models here.


class Subject(models.Model):
    name = models.CharField(max_length=20, unique=True)
    credit_points = models.IntegerField(validators=[MaxValueValidator(10)])

    class Meta:
        verbose_name = 'Subject'
        verbose_name_plural = 'Subjects'

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(unique=True, max_length=50)
    subjects = models.ManyToManyField(Subject)

    class Meta:
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

    def __str__(self):
        return self.name

    def get_sub_values(self):
        return self.subjects.filter(course__subjects__in=self.name)


class Student(models.Model):
    name = models.CharField(max_length=25)
    roll_num = models.IntegerField(unique=True)
    courses = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

    def __str__(self):
        return self.name


class Lecturer(models.Model):
    name = models.CharField(max_length=25)
    subjects_taken = models.ForeignKey(Subject, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Lecturer'
        verbose_name_plural = 'Lecturers'

    def __str__(self):
        return self.name

myapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question,Choice
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'myapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'myapp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'myapp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('myapp:results', args=(question.id,)))

student/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.apps import apps

# Create your views here.
import student
from student.models import Student, Lecturer, Course, Subject


def homeview(request):
    return render(request, 'home.html')


def studentlistView(request):
    total_list = Student.objects.order_by('roll_num')
    context = {'total_list': total_list}
    return render(request, 'studentlist.html', context)


def lecturerslistView(request):
    total_list = Lecturer.objects.order_by('name')
    context = {'total_list': total_list}
    return render(request, 'lecturerlist.html', context)


def courselistView(request):
    total_list = Course.objects.order_by('name')
    context = {
        'total_list': total_list,
               }
    return render(request, 'courselist.html', context)


def subjectslistView(request):
    total_list = Subject.objects.order_by('name')
    context = {'total_list': total_list}
    return render(request, 'subjectlist.html', context)


def coursedetailView(request, record_id):
    selected_course = Course.objects.get(id=record_id)
    subjects_included = selected_course.subjects.all()
    context = {
        'selected_course':selected_course,
        'subjects_included':subjects_included
    }
    return render(request, 'details.html', context)


def subjectlecturerView(request, record_id):
    selected_subject = Subject.objects.get(id=record_id)
    lecturers_list = selected_subject.lecturer_set.all()
    context = {
        'selected_subject':selected_subject,
        'lecturers_list':lecturers_list

    }
    return render(request, 'subjectlecture.html', context)

myapp/templates/myapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

</body>
</html>

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'myapp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

myapp/templates/myapp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'myapp:detail' question.id %}">Vote again?</a>


</body>
</html>

student/templates/courselist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Course List</h3>
        <ul>
        {% for record in total_list %}
           <li><a href="{% url 'student:coursedetailView' record.id %}">{{ record.name }}</a></li>
        {% endfor %}
        </ul>

</body>
</html>

student/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Subjects in {{ selected_course }}</h2>
<ul>
    {% for rec in subjects_included %}
        <li><a href="{% url 'student:subjectlecturerView' rec.id%}">{{ rec.name }}</a></li>
    {% endfor %}
</ul>
<ul>

</ul>

</body>
</html>

student/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Collage</title>
</head>
<body>

<h1>RV Collage </h1>
<ul>
{#    {% for list in total_list %}#}
{#        <h2><li><a > {{ list }}</a> </li></h2>#}
{#    {% endfor %}#}
    <h2><li><a href="{% url 'student:studentlistView' %}">Students</a> </li></h2>
    <h2><li><a href="{% url 'student:lecturerslistView' %}">Lecturers</a> </li></h2>
    <h2><li><a href="{% url 'student:courselistView' %}">Courses Offered</a> </li></h2>
    <h2><li><a href="{% url 'student:subjectslistView' %}">Subjects</a> </li></h2>


</ul>
</body>
</html>

student/templates/lecturerlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <table border="1px">
        <th>Lecturer Name</th>
        <th>Subject</th>
        {% for record in total_list %}
            <tr>
                <td>{{ record.name }}</td>
                <td>{{ record.subjects_taken }}</td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>

student/templates/studentlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table border="1px">
        <th>Roll No:</th>
        <th>Student Name</th>
        <th>Course Taken</th>
        {% for stud in total_list %}
            <tr>
                <td>{{ stud.roll_num }}</td>
                <td>{{ stud.name }}</td>
                <td><a href="{% url 'student:coursedetailView' stud.courses.id %}">{{ stud.courses }}</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

student/templates/subjectlecture.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% if lecturers_list.count > 0 %}
        <h2>{{ selected_subject }} Lecturers</h2>
        {% for rec in lecturers_list %}
            <ul><h3><li> {{ rec.name }} </li></h3></ul>
        {% endfor %}
        {% if lecturers_list.count == 1 %}
            <h3>Total {{ lecturers_list.count }} Lecturer</h3>
            {% else %}
                <h3>Total {{ lecturers_list.count }} Lecturers</h3>
        {% endif %}
    {% else %}
        <h3>Sorry there are no Lecturers for {{ selected_subject }} Subject.</h3>
    {% endif %}

</body>
</html>

student/templates/subjectlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <table border="1px">
        <th>Subject Name</th>
        <th>Minimum Credit</th>
        {% for record in total_list %}
            <tr>
                <td><a href="{% url 'student:subjectlecturerView' record.id%}">{{ record.name }}</a></td>
                <td>{{ record.credit_points }}</td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>